### ISSUE TITLE
Feature Request: Separate Directives in Settings

### ISSUE THREAD

**Issue by oreoshake** [c0nrad/enforcer#1]
It would be cool if each directive were it's own text field, it's easy to get lost in a long policy.

**Comment by c0nrad** [comment]
Hey Neil! I added separate text fields for each of the directives:

You can modify the policy string:
http://gyazo.com/b6cc88fe854971f3cdc27429e22eeabb

Or the directive:
http://gyazo.com/77876a9070fbe90e4843883f22c94312

What do you think? 
c0nrad

**Comment by oreoshake** [comment]
:metal:

**Comment by c0nrad** [comment]
lol, changes pushed.

thanks for the feedback
